//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSoldierDeathTeam.DataBaseLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GamePlatforms = new HashSet<GamePlatform>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int GameCategoryId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Developer { get; set; }
        public string Publisher { get; set; }
        public string RecommendedOS { get; set; }
        public string RecommendedCPU { get; set; }
        public string RecommendedGPU { get; set; }
        public string RecommendedRAM { get; set; }
        public string RecommendedHDD { get; set; }
    
        public virtual GameCategory GameCategory { get; set; }
        public virtual ICollection<GamePlatform> GamePlatforms { get; set; }
    }
}
