//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSoldierDeathTeam.DataBaseLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public bool IsSenderDeleted { get; set; }
        public bool IsRecipientDeleted { get; set; }
        public bool IsSenderSaved { get; set; }
        public bool IsRecipientSaved { get; set; }
    
        public virtual User Recipient { get; set; }
        public virtual User Sender { get; set; }
    }
}
