//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSoldierDeathTeam.DataBaseLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.NewsPlatforms = new HashSet<NewsPlatform>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CountViews { get; set; }
        public Nullable<int> GameCategoryId { get; set; }
        public int WriterId { get; set; }
    
        public virtual GameCategory GameCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<NewsPlatform> NewsPlatforms { get; set; }
    }
}
