//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueSoldierDeathTeam.DataBaseLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExternalInfo
    {
        public UserExternalInfo()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string ProviderName { get; set; }
        public string ProviderKey { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
